name: CI/CD Backend Pipeline
on:
  push:
    branches:
      - deploy
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3
      - name: Configurar AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1
      - name: Login a Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Construir y Subir imágenes a ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: tienda-backend
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:despachos-latest ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:despachos-latest
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:ventas-latest ./back-Ventas_SpringBoot/Springboot-API-REST
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:ventas-latest
      - name: Despliegue en EC2 usando AWS SSM
        run: |
          aws ssm send-command \
            --instance-ids "${{ secrets.EC2_INSTANCE_ID }}" \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=[
              "aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 447858402230.dkr.ecr.us-east-1.amazonaws.com",
              "docker pull 447858402230.dkr.ecr.us-east-1.amazonaws.com/tienda-backend:despachos-latest",
              "docker pull 447858402230.dkr.ecr.us-east-1.amazonaws.com/tienda-backend:ventas-latest",
              "docker stop tienda-backend-despachos || true",
              "docker stop tienda-backend-ventas || true",
              "docker rm tienda-backend-despachos || true",
              "docker rm tienda-backend-ventas || true",
              "docker run -d --name tienda-backend-despachos -p 8081:8081 -e DB_ENDPOINT=172.31.11.7 -e DB_PORT=3306 -e DB_NAME=tienda_perritos -e DB_USERNAME=root -e DB_PASSWORD=admin123 447858402230.dkr.ecr.us-east-1.amazonaws.com/tienda-backend:despachos-latest",
              "docker run -d --name tienda-backend-ventas -p 8082:8082 -e DB_ENDPOINT=172.31.11.7 -e DB_PORT=3306 -e DB_NAME=tienda_perritos -e DB_USERNAME=root -e DB_PASSWORD=admin123 447858402230.dkr.ecr.us-east-1.amazonaws.com/tienda-backend:ventas-latest"
            ]'
